language: php

sudo: false

env:
    global:
      - ES_VERSION="2.4.4"
      - ES_DOWNLOAD_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.zip"

matrix:
  include:
    - php: 5.5
      env:
        - PREFER="--prefer-lowest"
        - SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 5.5
      env:
        - PREFER=""
        - SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 5.6
      env:
        - PREFER=""
        - SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.3
      env:
        - PREFER=""
        - SYMFONY_DEPRECATIONS_HELPER=strong

before_install:
  - curl -L -o elasticsearch.zip ${ES_DOWNLOAD_URL}
  - ls -lah
  - unzip elasticsearch.zip
  - phpenv config-rm xdebug.ini
  - phpenv config-add Tests/travis.php.ini
  - composer self-update

before_script:
    - composer require elasticsearch/elasticsearch:^2.1 --dev --no-update
    - composer update $PREFER
    - elasticsearch-*/bin/elasticsearch -d
    - wget -q --waitretry=2 --retry-connrefused -T 20 -O - http://127.0.0.1:9200

script: 
    - vendor/bin/phpunit --coverage-text
    - vendor/bin/behat --suite=zend_lucene
    - vendor/bin/behat --suite=elastic

cache:
  directories:
    - $HOME/.composer/cache
