language: php

sudo: false
dist: trusty

env:
    global:
      - ES_VERSION="2.4.4"
      - ES_DOWNLOAD_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.zip"

matrix:
  include:
    - php: 7.2
      env:
        - PREFER="--prefer-lowest"
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - ENABLE_SWAP=true
    - php: 7.4
      env:
        - PREFER=""
        - SYMFONY_DEPRECATIONS_HELPER=strong

before_install:
  - curl -L -o elasticsearch.zip ${ES_DOWNLOAD_URL}
  - ls -lah
  - | # enable swap
    if [[ $ENABLE_SWAP == 'true' ]]; then
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo sysctl vm.swappiness=20
    fi
  - unzip elasticsearch.zip
  - phpenv config-rm xdebug.ini || true
  - phpenv config-add Tests/travis.php.ini
  - composer self-update

before_script:
    - composer require elasticsearch/elasticsearch:^2.1 --dev --no-update
    - composer update --prefer-dist $PREFER
    - elasticsearch-*/bin/elasticsearch -d
    - wget -q --waitretry=2 --retry-connrefused -T 20 -O - http://127.0.0.1:9200

script:
    - vendor/bin/phpunit --coverage-text
    - vendor/bin/behat --suite=zend_lucene
    - vendor/bin/behat --suite=elastic

cache:
  directories:
    - $HOME/.composer/cache
