language: php

services:
  - elasticsearch

sudo: false

php:
  - 5.4

before_script:
  - composer selfupdate
  - composer install --dev

script: 
    - phpunit --coverage-text
    - vendor/behat/behat/bin/behat --suite=zend_lucene
    - vendor/behat/behat/bin/behat --suite=elastic
